# Generated by Django 5.0.7 on 2024-08-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.CharField(default="", max_length=111),
        ),
    ]
